---
- hosts: webservers
  sudo: yes

  vars_files:
    - ../vars.yml
    - vars.yml

  pre_tasks:
    # Add backports so we can install a newer version of Nginx.
    - include: ../wheezy-backports.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.nginx
    - geerlingguy.php
    - geerlingguy.drush
    - geerlingguy.git
    - geerlingguy.munin-node
    - geerlingguy.nfs
    - ../roles/leds

  tasks:
    - include: tasks/extras.yml
    - include: tasks/config.yml
    - include: tasks/nfs.yml
    - include: tasks/led-monitor.yml
